// Photo Gallery page (photo-gallery.html) — cursor-trail photo wall.
// Vanilla-JS port of a Claude Design brutalism prototype
// (reference/gaming-exploration.md has the workflow for adding photos).
// Moving the pointer spawns a photo chip under it that fades out on its
// own after a few seconds — purely decorative, clicking a chip does
// nothing. Scroll to resize future chips (and preview the resize on the
// one just spawned), double-click to reset.
(() => {
  "use strict";

  // This page shows real photography — images/gallery/ via
  // js/gallery-manifest.js (regenerated by
  // scripts/build-gallery-manifest.ps1). No captions or metadata are shown,
  // just the photos. (Gaming screenshots live in images/gaming/ and are
  // shown on gaming-gallery.html instead — see
  // reference/gaming-exploration.md.)
  const photoFiles = window.GALLERY_PHOTOS || [];
  const SHOTS = photoFiles.map((file) => "images/gallery/" + encodeURIComponent(file));

  const root = document.getElementById("gmRoot");
  const plane = document.getElementById("gmPlane");
  const proto = document.getElementById("gmProto");
  const empty = document.getElementById("gmEmpty");
  const hint = document.getElementById("gmHint");
  const sizeEl = document.getElementById("gmSizeValue");
  const resetBtn = document.getElementById("gmReset");
  if (!root || !plane || !proto) return;

  if (!SHOTS.length) {
    empty.hidden = false;
    if (hint) hint.hidden = true;
    return;
  }

  const LIFE = 3000;        // ms a chip stays before it starts fading
  const SPAWN_MS = 85;      // throttle: minimum time between spawns
  const SPAWN_PX = 60;      // throttle: minimum cursor travel between spawns
  const EASE = "cubic-bezier(.2,.8,.2,1)";
  const IN_MS = 380;
  const OUT_MS = 620;
  const BASE_W = 300;       // clamp floor — matches 100% in the readout
  const MAX_W = 660;
  const STACK_CAP = 22;     // safety valve if the cursor outruns the fade cycle

  let size = 1;
  let live = null;    // the most recently spawned chip — scroll-to-resize previews on this one
  const chips = [];
  let last = { t: 0, x: -9999, y: -9999 };
  let next = 0;

  function baseWidthNow() {
    return window.innerWidth <= 640 ? 220 : BASE_W;
  }

  function dismissHint() {
    if (!hint || hint.dataset.done) return;
    hint.dataset.done = "1";
    hint.style.opacity = "0";
    try { localStorage.setItem("gaming-hint", "done"); } catch (e) {}
  }

  function exit(chip) {
    if (!chip || chip.gone) return;
    chip.gone = true;
    clearTimeout(chip.timer);
    const el = chip.el;
    el.style.pointerEvents = "none";
    el.style.transition = "opacity " + OUT_MS + "ms " + EASE + ",filter " + OUT_MS + "ms " + EASE + ",transform " + OUT_MS + "ms " + EASE;
    el.style.opacity = "0";
    el.style.filter = "blur(7px)";
    el.style.transform = "rotate(" + chip.rot.toFixed(2) + "deg) translateY(30px) scale(.9)";
    const drop = () => {
      el.remove();
      const i = chips.indexOf(chip);
      if (i !== -1) chips.splice(i, 1);
      if (live === chip) live = null;
    };
    el.addEventListener("transitionend", drop, { once: true });
    setTimeout(drop, OUT_MS + 160);
  }

  // Cycles through SHOTS forever regardless of how few photos there are
  // (next just keeps counting up) — only ever called from pointer/touch
  // movement, throttled below.
  function spawnAt(x, y) {
    const now = performance.now();
    const far = Math.hypot(x - last.x, y - last.y) > SPAWN_PX;
    if (now - last.t < SPAWN_MS && !far) return;
    last = { t: now, x, y };
    dismissHint();

    const src = SHOTS[next % SHOTS.length];
    next++;

    const el = proto.cloneNode(true);
    el.removeAttribute("id");
    el.setAttribute("aria-hidden", "true");
    const w = Math.round(baseWidthNow() * size);
    const jx = (Math.random() - 0.5) * 34;
    const jy = (Math.random() - 0.5) * 34;
    const rot = (Math.random() - 0.5) * 13;
    el.style.display = "block";
    el.style.width = w + "px";
    el.style.left = Math.round(x - w / 2 + jx) + "px";
    el.style.top = Math.round(y - w * 0.42 + jy) + "px";
    el.style.zIndex = String(100 + (next % 400));
    el.style.opacity = "0";
    el.style.filter = "blur(12px)";
    el.style.transform = "rotate(" + rot.toFixed(2) + "deg) scale(.8)";
    el.style.transition = "opacity " + IN_MS + "ms " + EASE + ",filter " + IN_MS + "ms " + EASE + ",transform " + IN_MS + "ms " + EASE;
    el.style.pointerEvents = "none"; // decorative only — a click on a chip does nothing

    const photo = el.querySelector(".gm-card__photo");
    if (photo) photo.style.background = '#FF4FA3 url("' + src + '") center/cover no-repeat';

    const chip = { el, rot, timer: 0, born: now };
    plane.appendChild(el);
    chips.push(chip);
    requestAnimationFrame(() => {
      el.style.opacity = "1";
      el.style.filter = "blur(0px)";
      el.style.transform = "rotate(" + rot.toFixed(2) + "deg) scale(1)";
    });

    live = chip;

    chip.timer = setTimeout(() => exit(chip), LIFE);
    trimStack(chip);
  }

  // Keeps `chips` bounded at STACK_CAP even if the cursor outruns the fade
  // cycle. exit() doesn't remove a chip from `chips` synchronously — it
  // only starts the fade and removes it later (on transitionend or a
  // fallback timer) — so this splices it out of the array immediately
  // itself. Every pass either shrinks the array or advances past the
  // just-spawned chip; it never re-inspects the same untouched front
  // element twice, which is what let this loop spin forever and lock up
  // the tab before.
  function trimStack(skip) {
    let i = 0;
    while (chips.length > STACK_CAP && i < chips.length) {
      const c = chips[i];
      if (c === skip) { i++; continue; }
      chips.splice(i, 1);
      exit(c);
    }
  }

  function paintSize() {
    if (sizeEl) sizeEl.textContent = Math.round(size * 100) + "%";
  }

  function zoom(dir) {
    const step = 0.12;
    const min = 1;
    const max = MAX_W / BASE_W;
    size = Math.min(max, Math.max(min, size + dir * step));
    if (live && live.el.isConnected) {
      const w = Math.round(baseWidthNow() * size);
      const rect = live.el.getBoundingClientRect();
      const cx = rect.left + rect.width / 2, cy = rect.top + rect.height / 2;
      live.el.style.width = w + "px";
      live.el.style.left = Math.round(cx - w / 2) + "px";
      live.el.style.top = Math.round(cy - w * 0.42) + "px";
    }
    paintSize();
  }
  function resetSize() {
    size = 1;
    paintSize();
  }

  root.addEventListener("pointermove", (e) => spawnAt(e.clientX, e.clientY));
  root.addEventListener("touchmove", (e) => {
    const t = e.touches && e.touches[0];
    if (t) spawnAt(t.clientX, t.clientY);
  }, { passive: true });
  root.addEventListener("wheel", (e) => { e.preventDefault(); zoom(e.deltaY < 0 ? 1 : -1); }, { passive: false });
  root.addEventListener("dblclick", resetSize);
  root.addEventListener("contextmenu", (e) => e.preventDefault());
  resetBtn.addEventListener("click", resetSize);

  try { if (localStorage.getItem("gaming-hint") === "done") dismissHint(); } catch (e) {}

  paintSize();
})();
