# Scans images/gallery/ and regenerates js/gallery-manifest.js so the Photo
# Gallery page (photo-gallery.html) shows every photo in that folder
# automatically.
#
# Run this (or double-click scripts/update-gallery.bat) any time you add or
# remove a photo in images/gallery/, then refresh the page. Captions are
# optional — add them in js/gallery-data.js, keyed by filename.

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$galleryDir = Join-Path $root "images\gallery"
$manifestPath = Join-Path $root "js\gallery-manifest.js"

if (-not (Test-Path $galleryDir)) {
    Write-Error "images/gallery folder not found at $galleryDir"
    exit 1
}

$exts = @(".jpg", ".jpeg", ".png", ".webp")
$files = Get-ChildItem -Path $galleryDir -File |
    Where-Object { $exts -contains $_.Extension.ToLower() } |
    Sort-Object Name

$entries = $files | ForEach-Object { '  "' + $_.Name.Replace('"', '\"') + '"' }
$list = $entries -join ",`n"

$out = @"
// AUTO-GENERATED by scripts/build-gallery-manifest.ps1 - do not edit by
// hand, your changes will be overwritten. Run that script (or double-click
// scripts/update-gallery.bat) after adding or removing files in
// images/gallery/, then refresh the page. Add captions in
// js/gallery-data.js - optional, keyed by filename.
window.GALLERY_PHOTOS = [
$list
];
"@

Set-Content -Path $manifestPath -Value $out -Encoding utf8
Write-Output ("Wrote " + $files.Count + " photo(s) to js/gallery-manifest.js")
