# Scans images/gaming/ and regenerates js/gaming-manifest.js so the Gaming
# & Exploration page (gaming-gallery.html) shows every photo in that folder
# automatically.
#
# Run this (or double-click scripts/update-gaming.bat) any time you add or
# remove a photo in images/gaming/, then refresh the page. Captions are
# optional — add them in js/gaming-data.js, keyed by filename.

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$gamingDir = Join-Path $root "images\gaming"
$manifestPath = Join-Path $root "js\gaming-manifest.js"

if (-not (Test-Path $gamingDir)) {
    Write-Error "images/gaming folder not found at $gamingDir"
    exit 1
}

$exts = @(".jpg", ".jpeg", ".png", ".webp")
$files = Get-ChildItem -Path $gamingDir -File |
    Where-Object { $exts -contains $_.Extension.ToLower() } |
    Sort-Object Name

$entries = $files | ForEach-Object { '  "' + $_.Name.Replace('"', '\"') + '"' }
$list = $entries -join ",`n"

$out = @"
// AUTO-GENERATED by scripts/build-gaming-manifest.ps1 - do not edit by
// hand, your changes will be overwritten. Run that script (or double-click
// scripts/update-gaming.bat) after adding or removing files in
// images/gaming/, then refresh the page. Add captions in
// js/gaming-data.js - optional, keyed by filename.
window.GAMING_PHOTOS = [
$list
];
"@

Set-Content -Path $manifestPath -Value $out -Encoding utf8
Write-Output ("Wrote " + $files.Count + " photo(s) to js/gaming-manifest.js")
