# Regenerates the Open Graph / Twitter Card meta block in every page
# listed in seo-data.json, from that one file - so a title/description
# only ever gets typed once. Run this (or double-click
# scripts/update-seo.bat) after editing seo-data.json.
#
# This does NOT touch each page's own <title>/<meta name="description">
# tags - several of them carry an id (e.g. <title id="aboutPageTitle">)
# that page's own JS updates at runtime (see about.js, experiments.js,
# the case-study renderers). Rewriting those here would either strip that
# id and silently break that JS, or risk drifting from the *-data.js file
# that actually owns that page's on-screen copy. Instead this only
# manages a clearly-marked, purely additive block of og:/twitter: tags -
# see reference/seo-metadata.md for the full picture, including why that
# split exists and what to keep in sync by hand.
#
# Social crawlers (Twitter/X, Facebook, LinkedIn, Slack, Discord...) read
# raw HTML only, no JavaScript - these tags have to be static in the file
# already, they can't be set at runtime the way document.title is.

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$dataPath = Join-Path $root "seo-data.json"

# Windows PowerShell 5.1's Get-Content/Set-Content silently guess a
# codepage on files with no BOM, which corrupts every em dash/arrow/etc.
# on read AND on write-back (this bit once already - see git history).
# Reading and writing raw bytes through .NET's UTF8Encoding directly
# sidesteps that guessing entirely, BOM or not.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
function ReadUtf8([string]$path) { return [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8) }
function WriteUtf8([string]$path, [string]$text) { [System.IO.File]::WriteAllText($path, $text, $utf8NoBom) }

$data = ReadUtf8 $dataPath | ConvertFrom-Json

$startMarker = "<!-- SEO:START (generated by scripts/sync-seo-meta.ps1 from seo-data.json - do not hand-edit this block) -->"
$endMarker = "<!-- SEO:END -->"

function HtmlEscape([string]$s) {
    return $s -replace "&", "&amp;" -replace '"', "&quot;" -replace "<", "&lt;" -replace ">", "&gt;"
}

$updated = 0
foreach ($page in $data.pages) {
    $filePath = Join-Path $root $page.path
    if (-not (Test-Path $filePath)) {
        Write-Warning ("Skipping " + $page.path + " - file not found")
        continue
    }

    $url = if ($page.path -eq "index.html") { $data.site.baseUrl + "/" } else { $data.site.baseUrl + "/" + $page.path }
    $imagePath = if ($page.image) { $page.image } else { $data.site.defaultImage }
    $image = $data.site.baseUrl + "/" + $imagePath

    $title = HtmlEscape $page.title
    $description = HtmlEscape $page.description
    $urlEsc = HtmlEscape $url
    $imageEsc = HtmlEscape $image
    $typeEsc = HtmlEscape $page.type
    $siteNameEsc = HtmlEscape $data.site.name
    $cardEsc = HtmlEscape $data.site.twitterCard

    $block = @"
$startMarker
<meta property="og:type" content="$typeEsc">
<meta property="og:url" content="$urlEsc">
<meta property="og:title" content="$title">
<meta property="og:description" content="$description">
<meta property="og:image" content="$imageEsc">
<meta property="og:site_name" content="$siteNameEsc">
<meta name="twitter:card" content="$cardEsc">
<meta name="twitter:title" content="$title">
<meta name="twitter:description" content="$description">
<meta name="twitter:image" content="$imageEsc">
$endMarker
"@

    $content = ReadUtf8 $filePath
    $blockPattern = [regex]::Escape($startMarker) + "[\s\S]*?" + [regex]::Escape($endMarker)

    if ($content -match $blockPattern) {
        # MatchEvaluator inserts $block completely literally - no
        # backreference/escaping surprises from a "$" or "\" inside it.
        $content = [regex]::Replace($content, $blockPattern, { param($m) $block })
    } else {
        $content = $content -replace "</head>", ("  " + $block + "`r`n</head>")
    }

    WriteUtf8 $filePath $content
    $updated++
    Write-Output ("Updated " + $page.path)
}

Write-Output ""
Write-Output ($updated.ToString() + " page(s) synced from seo-data.json.")
